# Helix repository configuration
#
# This file configures Helix behavior for this repository.
# Settings here override global settings in ~/.helix.toml

[user]
# Author information for commits
# Uncomment and set these, or use environment variables:
#   HELIX_AUTHOR_NAME, HELIX_AUTHOR_EMAIL
name = "Your Name"
email = "you@example.com"


[remotes]
origin_pull = "git@github.com:evisdrenova/helix-test.git"
origin_push = "git@github.com:evisdrenova/helix-test.git"

[ignore]
patterns = [
    "target/",
    "*.tmp",
    "*.log",
    ".helix/",
    ".git/"
]
